apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: validate-docker-sock-mount
spec:
  severity: 5
  message: "Use of the Docker Unix socket is not allowed."
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: ubuntu20
  file:
    matchPaths:
    - path: /var/run/docker.sock
  action:
    Audit